### ISSUE TITLE
ORA-00933: SQL command not terminated properly

### ISSUE THREAD

**Issue by zhaori96** [phenpessoa/sql2go#1]
When parsing queries, the ';' is retained at the end of the query, causing an error on the Oracle database. The package should provide a way to remove the ';' from the end of parsed queries.

However, it's worth noting that when dealing with a BEGIN ... END statement, the ';' is required at the end of this type of query.

**Comment by phenpessoa** [comment]
Hi @zhaori96

Thanks for the suggestion. Could you check if commit 7d1170e9c089e4ab6dfce1211f85af248bdfabab solves this for you please?

Basically I implemented a new `options` feature, where the caller can pass options to the parser.
Currently, there is only one option available: `remove-trailing-semicolon`.
By default, the trailing semicolon will be saved in the query, but if you pass this option, then it will not.

To test this you can run
```bash
go get github.com/phenpessoa/sql2go@7d1170e9c089e4ab6dfce1211f85af248bdfabab
```

and pass the options like this, for example:

```go
package main

import (
	"fmt"
	"strings"

	"github.com/phenpessoa/sql2go"
)

type Foo struct {
	Bar string
	Baz string
}

var input = `
-- name: Bar
-- options: remove-trailing-semicolon
SELECT * FROM bar;

-- name: Baz
SELECT * FROM baz;`

func main() {
	var f Foo
	if err := sql2go.Parse(&f, strings.NewReader(input)); err != nil {
		panic(err)
	}

	// f.Bar will not have the trailing semicolon
	fmt.Println(f.Bar) // SELECT * FROM bar

	// f.Baz will have the trailing semicolon
	fmt.Println(f.Baz) // SELECT * FROM baz;
}

```

**Comment by zhaori96** [comment]
It's working well now. Thanks for adding the new feature!
